In [1]:
import csv
import json
import pandas as pd

In [2]:
#read the csv file into a dataframe
hotels_df = pd.read_csv("static/data/hotels.csv")
hotels_df

,category,rank,name,location,imageurl,description,latitude,longitude,ratingurl
0,hotels,1,Tulemar Bungalows & Villas,"Manuel Antonio, Costa Rica",https://media-cdn.tripadvisor.com/media/photo-...,The perfect vacation. The best part was simply...,9.410729,-84.155762,/Hotel_Review-g309274-d300974-Reviews-Tulemar_...
1,hotels,2,Hotel Colline de France,"Gramado, Brazil",https://media-cdn.tripadvisor.com/media/photo-...,"Whether on a honeymoon or family vacation, you...",-29.378749,-50.872494,/Hotel_Review-g303536-d13871137-Reviews-Hotel_...
2,hotels,3,Ikos Aria,"Kefalos, Greece",https://media-cdn.tripadvisor.com/media/photo-...,An absolutely beautiful hotel in the most stun...,36.745022,26.959521,/Hotel_Review-g910630-d15182081-Reviews-Ikos_A...
3,hotels,4,Romance Istanbul Hotel,"Istanbul, Turkiye",https://media-cdn.tripadvisor.com/media/photo-...,"The geographical location is one thing, howeve...",41.009198,28.966219,/Hotel_Review-g293974-d8364987-Reviews-Romance...
4,hotels,5,THE OMNIA,"Zermatt, Switzerland",https://media-cdn.tripadvisor.com/media/photo-...,Everything was perfect: the Bond-like cave ent...,46.021208,7.749254,/Hotel_Review-g188098-d619925-Reviews-THE_OMNI...
5,hotels,6,Kayakapi Premium Caves - Cappadocia,"Urgup, Turkiye",https://media-cdn.tripadvisor.com/media/photo-...,It felt so special to not only stay in an orig...,38.630051,34.911603,/Hotel_Review-g297989-d4090921-Reviews-Kayakap...
6,hotels,7,Six Senses Laamu,"Olhuveli Island, Maldives",https://media-cdn.tripadvisor.com/media/photo-...,We were encouraged to go barefoot and it helpe...,29.689689,-85.290566,/Hotel_Review-g2050017-d2045398-Reviews-Six_Se...
7,hotels,8,Hamanasi Adventure and Dive Resort,"Hopkins, Belize",https://media-cdn.tripadvisor.com/media/photo-...,The service is really amazing. We thought they...,16.863633,-88.284935,/Hotel_Review-g635532-d578879-Reviews-Hamanasi...
8,hotels,9,Padma Resort Ubud,"Payangan, Indonesia",https://media-cdn.tripadvisor.com/media/photo-...,Wow just wow! The setting and location are jus...,-8.425267,115.245521,/Hotel_Review-g15213439-d7907965-Reviews-Padma...
9,hotels,10,BLESS Hotel Madrid,"Madrid, Spain",https://media-cdn.tripadvisor.com/media/photo-...,"Not only is the place classy, elegant, and dyn...",40.416705,-3.703582,/Hotel_Review-g187514-d12877674-Reviews-BLESS_...
10,hotels,11,Ikos Dassia,"Dassia, Greece",https://media-cdn.tripadvisor.com/media/photo-...,"The staff canâ€™t seem to do enough for you, the...",39.680027,19.837897,/Hotel_Review-g939713-d12279503-Reviews-Ikos_D...
11,hotels,12,Pimalai Resort and Spa,"Ko Lanta, Krabi Province",https://media-cdn.tripadvisor.com/media/photo-...,Brilliant experience,7.531020,99.094384,/Hotel_Review-g303905-d302953-Reviews-Pimalai_...
12,hotels,13,Lotte Hotel Hanoi,"Hanoi, Vietnam",https://media-cdn.tripadvisor.com/media/photo-...,Sensational service - world class,21.029450,105.854444,/Hotel_Review-g293924-d5049935-Reviews-Lotte_H...
13,hotels,14,COMO Cocoa Island,"Cocoa Island, Maldives",https://media-cdn.tripadvisor.com/media/photo-...,Perfect - a home away from home!,3.917766,73.469553,/Hotel_Review-g6852301-d308275-Reviews-COMO_Co...
14,hotels,15,La Maison Favart,"Paris, France",https://media-cdn.tripadvisor.com/media/photo-...,Absolutely great in every way! Very friendly a...,48.853495,2.348391,/Hotel_Review-g187147-d232552-Reviews-La_Maiso...
15,hotels,16,"Sukhumvit Park, Bangkok - Marriott Executive A...","Bangkok, Thailand",https://media-cdn.tripadvisor.com/media/photo-...,Super hospitality,13.752494,100.493509,/Hotel_Review-g293916-d1509981-Reviews-Sukhumv...
16,hotels,17,Quinta Jardins do Lago,"Funchal, Portugal",https://media-cdn.tripadvisor.com/media/photo-...,As near perfection as one could reasonably exp...,32.649650,-16.908678,/Hotel_Review-g189167-d319673-Reviews-Quinta_J...
17,hotels,18,La Maison Arabe,"Marrakech, Morocco",https://media-cdn.tripadvisor.com/media/photo-...,Stay here and have an amazing trip!,31.625826,-7.989161,/Hotel_Review-g293734-d303075-Reviews-La_Maiso...
18,hotels,19,The Royal Purnama,"Sukawati, Indonesia",https://media-cdn.tripadvisor.com/media/photo-...,"A perfect relaxing and inspiring hotel, a must!",-8.596155,115.282039,/Hotel_Review-g2646686-d7621681-Reviews-The_Ro...
19,hotels,20,Jaya House River Park,"Siem Reap, Cambodia",https://media-cdn.tripadvisor.com/media/photo-...,Laidback luxuryâ€¦genuinely friendly not fake fu...,13.361756,103.859032,/Hotel_Review-g297390-d11966106-Reviews-Jaya_H...
20,hotels,21,The Hazelton Hotel,"Toronto, Ontario",https://media-cdn.tripadvisor.com/media/photo-...,"Welcoming Staff, Great Location",43.653482,-79.383935,/Hotel_Review-g155019-d656431-Reviews-The_Haze...
21,hotels,22,Round Hill Hotel and Villas,"Hopewell, Jamaica",https://media-cdn.tripadvisor.com/media/photo-...,Spectacular!,18.456843,-78.011912,/Hotel_Review-g2307447-d147496-Reviews-Round_H...
22,hotels,23,Saraye Ameriha Boutique Hotel,"Kashan, Iran",https://media-cdn.tripadvisor.com/media/photo-...,"Lovely ,nice ,traditional hotel in Kashan",33.987653,51.442886,/Hotel_Review-g680023-d7211229-Reviews-Saraye_...
23,hotels,24,Bucuti & Tara Beach Resort Aruba,"Palm - Eagle Beach, Aruba",https://media-cdn.tripadvisor.com/media/photo-...,"The resort is beautiful, the service outstandi...",12.574010,-70.040455,/Hotel_Review-g147249-d301462-Reviews-Bucuti_T...
24,hotels,25,The Oberoi Beach Resort Sahl Hasheesh,"Hurghada, Egypt",https://media-cdn.tripadvisor.com/media/photo-...,Amazing place,27.222556,33.830706,/Hotel_Review-g15516847-d302029-Reviews-The_Ob...

In [3]:
hotels_df['id'] = hotels_df['category'] + hotels_df['rank'].astype(str)
hotels_df = hotels_df.drop(['ratingurl'], axis=1)

In [4]:
hotels_df = hotels_df[['id','category','rank','location','imageurl','description','latitude','longitude']]
hotels_df

,id,category,rank,location,imageurl,description,latitude,longitude
0,hotels1,hotels,1,"Manuel Antonio, Costa Rica",https://media-cdn.tripadvisor.com/media/photo-...,The perfect vacation. The best part was simply...,9.410729,-84.155762
1,hotels2,hotels,2,"Gramado, Brazil",https://media-cdn.tripadvisor.com/media/photo-...,"Whether on a honeymoon or family vacation, you...",-29.378749,-50.872494
2,hotels3,hotels,3,"Kefalos, Greece",https://media-cdn.tripadvisor.com/media/photo-...,An absolutely beautiful hotel in the most stun...,36.745022,26.959521
3,hotels4,hotels,4,"Istanbul, Turkiye",https://media-cdn.tripadvisor.com/media/photo-...,"The geographical location is one thing, howeve...",41.009198,28.966219
4,hotels5,hotels,5,"Zermatt, Switzerland",https://media-cdn.tripadvisor.com/media/photo-...,Everything was perfect: the Bond-like cave ent...,46.021208,7.749254
5,hotels6,hotels,6,"Urgup, Turkiye",https://media-cdn.tripadvisor.com/media/photo-...,It felt so special to not only stay in an orig...,38.630051,34.911603
6,hotels7,hotels,7,"Olhuveli Island, Maldives",https://media-cdn.tripadvisor.com/media/photo-...,We were encouraged to go barefoot and it helpe...,29.689689,-85.290566
7,hotels8,hotels,8,"Hopkins, Belize",https://media-cdn.tripadvisor.com/media/photo-...,The service is really amazing. We thought they...,16.863633,-88.284935
8,hotels9,hotels,9,"Payangan, Indonesia",https://media-cdn.tripadvisor.com/media/photo-...,Wow just wow! The setting and location are jus...,-8.425267,115.245521
9,hotels10,hotels,10,"Madrid, Spain",https://media-cdn.tripadvisor.com/media/photo-...,"Not only is the place classy, elegant, and dyn...",40.416705,-3.703582
10,hotels11,hotels,11,"Dassia, Greece",https://media-cdn.tripadvisor.com/media/photo-...,"The staff canâ€™t seem to do enough for you, the...",39.680027,19.837897
11,hotels12,hotels,12,"Ko Lanta, Krabi Province",https://media-cdn.tripadvisor.com/media/photo-...,Brilliant experience,7.531020,99.094384
12,hotels13,hotels,13,"Hanoi, Vietnam",https://media-cdn.tripadvisor.com/media/photo-...,Sensational service - world class,21.029450,105.854444
13,hotels14,hotels,14,"Cocoa Island, Maldives",https://media-cdn.tripadvisor.com/media/photo-...,Perfect - a home away from home!,3.917766,73.469553
14,hotels15,hotels,15,"Paris, France",https://media-cdn.tripadvisor.com/media/photo-...,Absolutely great in every way! Very friendly a...,48.853495,2.348391
15,hotels16,hotels,16,"Bangkok, Thailand",https://media-cdn.tripadvisor.com/media/photo-...,Super hospitality,13.752494,100.493509
16,hotels17,hotels,17,"Funchal, Portugal",https://media-cdn.tripadvisor.com/media/photo-...,As near perfection as one could reasonably exp...,32.649650,-16.908678
17,hotels18,hotels,18,"Marrakech, Morocco",https://media-cdn.tripadvisor.com/media/photo-...,Stay here and have an amazing trip!,31.625826,-7.989161
18,hotels19,hotels,19,"Sukawati, Indonesia",https://media-cdn.tripadvisor.com/media/photo-...,"A perfect relaxing and inspiring hotel, a must!",-8.596155,115.282039
19,hotels20,hotels,20,"Siem Reap, Cambodia",https://media-cdn.tripadvisor.com/media/photo-...,Laidback luxuryâ€¦genuinely friendly not fake fu...,13.361756,103.859032
20,hotels21,hotels,21,"Toronto, Ontario",https://media-cdn.tripadvisor.com/media/photo-...,"Welcoming Staff, Great Location",43.653482,-79.383935
21,hotels22,hotels,22,"Hopewell, Jamaica",https://media-cdn.tripadvisor.com/media/photo-...,Spectacular!,18.456843,-78.011912
22,hotels23,hotels,23,"Kashan, Iran",https://media-cdn.tripadvisor.com/media/photo-...,"Lovely ,nice ,traditional hotel in Kashan",33.987653,51.442886
23,hotels24,hotels,24,"Palm - Eagle Beach, Aruba",https://media-cdn.tripadvisor.com/media/photo-...,"The resort is beautiful, the service outstandi...",12.574010,-70.040455
24,hotels25,hotels,25,"Hurghada, Egypt",https://media-cdn.tripadvisor.com/media/photo-...,Amazing place,27.222556,33.830706

In [5]:
hotels_df.dtypes

id              object
category        object
rank             int64
location        object
imageurl        object
description     object
latitude       float64
longitude      float64
dtype: object

In [23]:
hotels_df.to_csv('beaches_id.csv')

In [7]:
#read the csv file into a dataframe
hotelreviews_df = pd.read_csv("static/data/hotelreviews.csv")

In [9]:
hotelreviews_df

,category,rank,rate,total_reviews,excellent,very good,average,poor,terrible,id
0,hotels,1,5,"4,970","4,777",144,29,14,6,hotels1
1,hotels,2,5,"3,039","3,033",6,0,0,0,hotels2
2,hotels,3,5,"1,928","1,902",21,5,0,0,hotels3
3,hotels,4,5,"3,290","3,237",46,5,1,1,hotels4
4,hotels,5,5,"1,372","1,320",38,9,5,0,hotels5
5,hotels,6,5,"2,182","2,047",116,15,4,2,hotels6
6,hotels,7,5,"3,630","3,431",150,41,7,2,hotels7
7,hotels,8,5,"2,893","2,805",75,5,4,4,hotels8
8,hotels,9,5,"4,617","4,382",180,34,9,12,hotels9
9,hotels,10,5,638,574,29,17,7,11,hotels10
10,hotels,11,5,"3,094","2,996",85,14,0,0,hotels11
11,hotels,12,5,"3,265","2,842",307,64,41,12,hotels12
12,hotels,13,5,"2,273","2,065",169,20,11,7,hotels13
13,hotels,14,5,"1,678","1,559",88,26,4,1,hotels14
14,hotels,15,5,"2,119","1,765",291,48,9,6,hotels15
15,hotels,16,5,"1,951","1,616",275,43,11,6,hotels16
16,hotels,17,5,"2,394","2,223",151,17,1,2,hotels17
17,hotels,18,5,"3,292","2,865",127,15,7,7,hotels18
18,hotels,19,5,701,623,57,15,3,3,hotels19
19,hotels,20,5,"3,066","3,043",22,2,0,0,hotels20
20,hotels,21,5,"1,446","1,338",63,24,11,10,hotels21
21,hotels,22,5,"1,737","1,493",144,56,26,18,hotels22
22,hotels,23,5,896,821,54,10,8,3,hotels23
23,hotels,24,5,"8,508","7,673",604,146,52,33,hotels24
24,hotels,25,5,"2,209","1,992",139,40,21,17,hotels25

In [19]:
hotelreviews_df = hotelreviews_df.rename(columns={'very good':'very_good'})
hotelreviews_df

,id,category,rank,rate,total_reviews,excellent,very_good,average,poor,terrible
0,hotels1,hotels,1,5,"4,970","4,777",144,29,14,6
1,hotels2,hotels,2,5,"3,039","3,033",6,0,0,0
2,hotels3,hotels,3,5,"1,928","1,902",21,5,0,0
3,hotels4,hotels,4,5,"3,290","3,237",46,5,1,1
4,hotels5,hotels,5,5,"1,372","1,320",38,9,5,0
5,hotels6,hotels,6,5,"2,182","2,047",116,15,4,2
6,hotels7,hotels,7,5,"3,630","3,431",150,41,7,2
7,hotels8,hotels,8,5,"2,893","2,805",75,5,4,4
8,hotels9,hotels,9,5,"4,617","4,382",180,34,9,12
9,hotels10,hotels,10,5,638,574,29,17,7,11
10,hotels11,hotels,11,5,"3,094","2,996",85,14,0,0
11,hotels12,hotels,12,5,"3,265","2,842",307,64,41,12
12,hotels13,hotels,13,5,"2,273","2,065",169,20,11,7
13,hotels14,hotels,14,5,"1,678","1,559",88,26,4,1
14,hotels15,hotels,15,5,"2,119","1,765",291,48,9,6
15,hotels16,hotels,16,5,"1,951","1,616",275,43,11,6
16,hotels17,hotels,17,5,"2,394","2,223",151,17,1,2
17,hotels18,hotels,18,5,"3,292","2,865",127,15,7,7
18,hotels19,hotels,19,5,701,623,57,15,3,3
19,hotels20,hotels,20,5,"3,066","3,043",22,2,0,0
20,hotels21,hotels,21,5,"1,446","1,338",63,24,11,10
21,hotels22,hotels,22,5,"1,737","1,493",144,56,26,18
22,hotels23,hotels,23,5,896,821,54,10,8,3
23,hotels24,hotels,24,5,"8,508","7,673",604,146,52,33
24,hotels25,hotels,25,5,"2,209","1,992",139,40,21,17

In [21]:
hotelreviews_df['id'] = hotelreviews_df['category'] + hotelreviews_df['rank'].astype(str)

hotelreviews_df = hotelreviews_df[['id','category','rank','rate','total_reviews','excellent','very_good','average','poor','terrible']]
hotelreviews_df

,id,category,rank,rate,total_reviews,excellent,very_good,average,poor,terrible
0,hotels1,hotels,1,5,"4,970","4,777",144,29,14,6
1,hotels2,hotels,2,5,"3,039","3,033",6,0,0,0
2,hotels3,hotels,3,5,"1,928","1,902",21,5,0,0
3,hotels4,hotels,4,5,"3,290","3,237",46,5,1,1
4,hotels5,hotels,5,5,"1,372","1,320",38,9,5,0
5,hotels6,hotels,6,5,"2,182","2,047",116,15,4,2
6,hotels7,hotels,7,5,"3,630","3,431",150,41,7,2
7,hotels8,hotels,8,5,"2,893","2,805",75,5,4,4
8,hotels9,hotels,9,5,"4,617","4,382",180,34,9,12
9,hotels10,hotels,10,5,638,574,29,17,7,11
10,hotels11,hotels,11,5,"3,094","2,996",85,14,0,0
11,hotels12,hotels,12,5,"3,265","2,842",307,64,41,12
12,hotels13,hotels,13,5,"2,273","2,065",169,20,11,7
13,hotels14,hotels,14,5,"1,678","1,559",88,26,4,1
14,hotels15,hotels,15,5,"2,119","1,765",291,48,9,6
15,hotels16,hotels,16,5,"1,951","1,616",275,43,11,6
16,hotels17,hotels,17,5,"2,394","2,223",151,17,1,2
17,hotels18,hotels,18,5,"3,292","2,865",127,15,7,7
18,hotels19,hotels,19,5,701,623,57,15,3,3
19,hotels20,hotels,20,5,"3,066","3,043",22,2,0,0
20,hotels21,hotels,21,5,"1,446","1,338",63,24,11,10
21,hotels22,hotels,22,5,"1,737","1,493",144,56,26,18
22,hotels23,hotels,23,5,896,821,54,10,8,3
23,hotels24,hotels,24,5,"8,508","7,673",604,146,52,33
24,hotels25,hotels,25,5,"2,209","1,992",139,40,21,17

In [22]:
hotelreviews_df.dtypes

id               object
category         object
rank              int64
rate              int64
total_reviews    object
excellent        object
very_good         int64
average           int64
poor              int64
terrible          int64
dtype: object

In [21]:
beachreviews_df.to_csv('beachreviews_id.csv')

In [23]:
hotels_merged_df = hotels_df.merge(hotelreviews_df, on=['id','category','rank'])
hotels_merged_df

,id,category,rank,location,imageurl,description,latitude,longitude,rate,total_reviews,excellent,very_good,average,poor,terrible
0,hotels1,hotels,1,"Manuel Antonio, Costa Rica",https://media-cdn.tripadvisor.com/media/photo-...,The perfect vacation. The best part was simply...,9.410729,-84.155762,5,"4,970","4,777",144,29,14,6
1,hotels2,hotels,2,"Gramado, Brazil",https://media-cdn.tripadvisor.com/media/photo-...,"Whether on a honeymoon or family vacation, you...",-29.378749,-50.872494,5,"3,039","3,033",6,0,0,0
2,hotels3,hotels,3,"Kefalos, Greece",https://media-cdn.tripadvisor.com/media/photo-...,An absolutely beautiful hotel in the most stun...,36.745022,26.959521,5,"1,928","1,902",21,5,0,0
3,hotels4,hotels,4,"Istanbul, Turkiye",https://media-cdn.tripadvisor.com/media/photo-...,"The geographical location is one thing, howeve...",41.009198,28.966219,5,"3,290","3,237",46,5,1,1
4,hotels5,hotels,5,"Zermatt, Switzerland",https://media-cdn.tripadvisor.com/media/photo-...,Everything was perfect: the Bond-like cave ent...,46.021208,7.749254,5,"1,372","1,320",38,9,5,0
5,hotels6,hotels,6,"Urgup, Turkiye",https://media-cdn.tripadvisor.com/media/photo-...,It felt so special to not only stay in an orig...,38.630051,34.911603,5,"2,182","2,047",116,15,4,2
6,hotels7,hotels,7,"Olhuveli Island, Maldives",https://media-cdn.tripadvisor.com/media/photo-...,We were encouraged to go barefoot and it helpe...,29.689689,-85.290566,5,"3,630","3,431",150,41,7,2
7,hotels8,hotels,8,"Hopkins, Belize",https://media-cdn.tripadvisor.com/media/photo-...,The service is really amazing. We thought they...,16.863633,-88.284935,5,"2,893","2,805",75,5,4,4
8,hotels9,hotels,9,"Payangan, Indonesia",https://media-cdn.tripadvisor.com/media/photo-...,Wow just wow! The setting and location are jus...,-8.425267,115.245521,5,"4,617","4,382",180,34,9,12
9,hotels10,hotels,10,"Madrid, Spain",https://media-cdn.tripadvisor.com/media/photo-...,"Not only is the place classy, elegant, and dyn...",40.416705,-3.703582,5,638,574,29,17,7,11
10,hotels11,hotels,11,"Dassia, Greece",https://media-cdn.tripadvisor.com/media/photo-...,"The staff canâ€™t seem to do enough for you, the...",39.680027,19.837897,5,"3,094","2,996",85,14,0,0
11,hotels12,hotels,12,"Ko Lanta, Krabi Province",https://media-cdn.tripadvisor.com/media/photo-...,Brilliant experience,7.531020,99.094384,5,"3,265","2,842",307,64,41,12
12,hotels13,hotels,13,"Hanoi, Vietnam",https://media-cdn.tripadvisor.com/media/photo-...,Sensational service - world class,21.029450,105.854444,5,"2,273","2,065",169,20,11,7
13,hotels14,hotels,14,"Cocoa Island, Maldives",https://media-cdn.tripadvisor.com/media/photo-...,Perfect - a home away from home!,3.917766,73.469553,5,"1,678","1,559",88,26,4,1
14,hotels15,hotels,15,"Paris, France",https://media-cdn.tripadvisor.com/media/photo-...,Absolutely great in every way! Very friendly a...,48.853495,2.348391,5,"2,119","1,765",291,48,9,6
15,hotels16,hotels,16,"Bangkok, Thailand",https://media-cdn.tripadvisor.com/media/photo-...,Super hospitality,13.752494,100.493509,5,"1,951","1,616",275,43,11,6
16,hotels17,hotels,17,"Funchal, Portugal",https://media-cdn.tripadvisor.com/media/photo-...,As near perfection as one could reasonably exp...,32.649650,-16.908678,5,"2,394","2,223",151,17,1,2
17,hotels18,hotels,18,"Marrakech, Morocco",https://media-cdn.tripadvisor.com/media/photo-...,Stay here and have an amazing trip!,31.625826,-7.989161,5,"3,292","2,865",127,15,7,7
18,hotels19,hotels,19,"Sukawati, Indonesia",https://media-cdn.tripadvisor.com/media/photo-...,"A perfect relaxing and inspiring hotel, a must!",-8.596155,115.282039,5,701,623,57,15,3,3
19,hotels20,hotels,20,"Siem Reap, Cambodia",https://media-cdn.tripadvisor.com/media/photo-...,Laidback luxuryâ€¦genuinely friendly not fake fu...,13.361756,103.859032,5,"3,066","3,043",22,2,0,0
20,hotels21,hotels,21,"Toronto, Ontario",https://media-cdn.tripadvisor.com/media/photo-...,"Welcoming Staff, Great Location",43.653482,-79.383935,5,"1,446","1,338",63,24,11,10
21,hotels22,hotels,22,"Hopewell, Jamaica",https://media-cdn.tripadvisor.com/media/photo-...,Spectacular!,18.456843,-78.011912,5,"1,737","1,493",144,56,26,18
22,hotels23,hotels,23,"Kashan, Iran",https://media-cdn.tripadvisor.com/media/photo-...,"Lovely ,nice ,traditional hotel in Kashan",33.987653,51.442886,5,896,821,54,10,8,3
23,hotels24,hotels,24,"Palm - Eagle Beach, Aruba",https://media-cdn.tripadvisor.com/media/photo-...,"The resort is beautiful, the service outstandi...",12.574010,-70.040455,5,"8,508","7,673",604,146,52,33
24,hotels25,hotels,25,"Hurghada, Egypt",https://media-cdn.tripadvisor.com/media/photo-...,Amazing place,27.222556,33.830706,5,"2,209","1,992",139,40,21,17

In [24]:
hotels_merged_df.to_csv('hotels_merged.csv', index=False)

In [26]:
hotels_merged_df.to_json('hotels_merged.json', orient = 'records')

In [ ]:
# Function to convert a CSV to JSON
# Takes the file paths as arguments
def make_json(csvFilePath, jsonFilePath):
     
    # create a dictionary
    data = {}
     
    # Open a csv reader called DictReader
    with open(csvFilePath, encoding='utf-8') as csvf:
        csvReader = csv.DictReader(csvf)
         
        # Convert each row into a dictionary
        # and add it to data
        for rows in csvReader:
             
            # Assuming a column named 'No' to
            # be the primary key
            key = rows['Ranking']
            data[key] = rows
 
    # Open a json writer, and use the json.dumps()
    # function to dump data
    with open(jsonFilePath, 'w', encoding='utf-8') as jsonf:
        jsonf.write(json.dumps(data, indent=4))

In [ ]:
# Driver Code
 
# Decide the two file paths according to your
# computer system
csvFilePath = r'DestinationsTripAdvisor2023.csv'
jsonFilePath = r'destination.json'

In [ ]:
# Call the make_json function
make_json(csvFilePath, jsonFilePath)